[server]
headless = true
fileWatcherType = "none"
runOnSave = false
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
fastReruns = false
